name: Build and Push Docker Image

on:
  workflow_dispatch:  # Uruchomienie ręczne

jobs:
  dockerCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # Wybrane architektury
          push: true
          tags: |
            michael1099/fullstack_zad2:latest
            michael1099/fullstack_zad2:v1.0.${{ github.run_number }}
        env:
          DOCKER_BUILDKIT: 1
          ACTIONS_STEP_DEBUG: true


  updateConfigRepo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Config Repository
        uses: actions/checkout@v3
        with:
          repository: MichalSulima1999/config-repo
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config --global user.email "michal.sulima1999@gmail.com"
          git config --global user.name "MichalSulima1999"

      - name: Update Config Repo
        run: |
          sed -i 's|image: michael1099/fullstack_zad2:v1|image: michael1099/fullstack_zad2:v1.0.${{ github.run_number }}|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update image version"
          git push

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: updateConfigRepo

    steps:
      - name: Checkout Config Repository
        uses: actions/checkout@v2
        with:
          repository: MichalSulima1999/config-repo
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config --global user.email "michal.sulima1999@gmail.com"
          git config --global user.name "MichalSulima1999"

      - name: Update Kubernetes Manifests
        run: |
          sed -i 's|image: michael1099/fullstack_zad2:v1|image: michael1099/fullstack_zad2:v1.0.${{ github.run_number }}|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update image reference in Kubernetes manifests"
          git push
